-- Insert data into the tables
INSERT INTO Title (Title_Code, Title_Name, Title_Description, Min_ELO) 
VALUES 
    ('GM', 'Grandmaster', 'The highest title a chess player can attain', 2500),
    ('WGM', 'Woman Grandmaster', 'The highest title a female chess player can attain', 2300),
    ('IM', 'International Master', 'The second-highest title awarded by FIDE', 2400),
    ('WIM', 'Woman International Master', 'The second-highest title for female players', 2200),
    ('FM', 'FIDE Master', 'The third-highest title awarded by FIDE', 2300),
    ('WFM', 'Woman FIDE Master', 'The third-highest title for female players', 2100),
    ('CM', 'Candidate Master', 'The lowest-ranking FIDE title', 2200),
    ('WCM', 'Woman Candidate Master', 'The lowest-ranking FIDE title for female players', 2000),
    ('NM', 'National Master', 'National level master title', 2200),
    ('WNM', 'Woman National Master', 'National level master title for female players', 2000);

-- Then, insert players with title_id reference
INSERT INTO Player (First_Name, Last_Name, Age, Title_Id, ELO_Rating)
SELECT 
    p.First_Name,
    p.Last_Name,
    p.Age,
    t.Title_Id,
    p.ELO_Rating
FROM (VALUES
    -- Top Male GMs (2700+)
    ('Magnus', 'Carlsen', 33, 'GM', 2831),
    ('Fabiano', 'Caruana', 32, 'GM', 2803),
    ('Hikaru', 'Nakamura', 36, 'GM', 2802),
    ('Arjun', 'Erigaisi', 20, 'GM', 2800),
    ('Gukesh', 'Dommaraju', 18, 'GM', 2776),
    ('Nodirbek', 'Abdusattorov', 19, 'GM', 2767),
    ('Alireza', 'Firouzja', 20, 'GM', 2763),
    ('Ian', 'Nepomniachtchi', 33, 'GM', 2753),
    ('Yi', 'Wei', 24, 'GM', 2750),
    ('Viswanathan', 'Anand', 54, 'GM', 2750),
    ('Levon', 'Aronian', 41, 'GM', 2747),
    ('Wesley', 'So', 30, 'GM', 2747),
    ('Sergey', 'Karjakin', 34, 'GM', 2745),
    ('Alexander', 'Grischuk', 40, 'GM', 2744),
    ('Dominguez', 'Perez', 41, 'GM', 2741),
    ('Praggnanandhaa', 'R', 18, 'GM', 2740),
    ('Jan-Krzysztof', 'Duda', 26, 'GM', 2740),
    ('Quang Liem', 'Le', 32, 'GM', 2739),
    ('Liren', 'Ding', 31, 'GM', 2734),
    ('Hans', 'Niemann', 21, 'GM', 2734),
    ('Vincent', 'Keymer', 19, 'GM', 2733),
    ('Maxime', 'Vachier-Lagrave', 33, 'GM', 2732),
    ('Shakhriyar', 'Mamedyarov', 39, 'GM', 2732),
    ('Anish', 'Giri', 30, 'GM', 2730),

    -- Strong GMs (2650-2699)
    ('Peter', 'Svidler', 47, 'GM', 2699),
    ('Boris', 'Gelfand', 55, 'GM', 2698),
    ('Pentala', 'Harikrishna', 37, 'GM', 2697),
    ('Dmitry', 'Andreikin', 33, 'GM', 2696),
    ('Vladimir', 'Kramnik', 48, 'GM', 2695),
    ('Sam', 'Shankland', 32, 'GM', 2694),
    ('David', 'Navara', 38, 'GM', 2693),
    ('Bu', 'Xiangzhi', 38, 'GM', 2692),
    ('Radoslaw', 'Wojtaszek', 36, 'GM', 2691),
    ('Francisco', 'Vallejo Pons', 40, 'GM', 2690),

    -- Top Female Players
    ('Hou', 'Yifan', 29, 'GM', 2680),
    ('Ju', 'Wenjun', 32, 'GM', 2660),
    ('Aleksandra', 'Goryachkina', 25, 'GM', 2658),
    ('Koneru', 'Humpy', 36, 'GM', 2650),
    ('Anna', 'Muzychuk', 33, 'GM', 2645),
    ('Kateryna', 'Lagno', 34, 'GM', 2640),
    ('Mariya', 'Muzychuk', 31, 'GM', 2635),
    ('Alexandra', 'Kosteniuk', 39, 'GM', 2630),
    ('Tan', 'Zhongyi', 32, 'WGM', 2625),
    ('Lei', 'Tingjie', 26, 'WGM', 2620),

    -- Strong IMs and Rising Stars
    ('Nihal', 'Sarin', 19, 'GM', 2645),
    ('Raunak', 'Sadhwani', 18, 'GM', 2635),
    ('Christopher', 'Yoo', 16, 'IM', 2590),
    ('Abhimanyu', 'Mishra', 14, 'IM', 2585),
    ('Marc', 'Andria Maurizzi', 16, 'IM', 2580),
    ('Jonas', 'Bjerre', 19, 'IM', 2575),
    ('Leon', 'Mendonca', 17, 'IM', 2570),

    -- Female IMs and WGMs
    ('Bibisara', 'Assaubayeva', 19, 'WGM', 2520),
    ('Zhansaya', 'Abdumalik', 23, 'IM', 2515),
    ('Dinara', 'Wagner', 22, 'WIM', 2490),
    ('Nurgyul', 'Salimova', 20, 'WIM', 2485),
    ('Zhu', 'Jiner', 21, 'WGM', 2480),

    -- National Masters and FMs
    ('Maximillian', 'Lu', 18, 'FM', 2450),
    ('Andrew', 'Tang', 23, 'FM', 2445),
    ('Daniel', 'Naroditsky', 28, 'FM', 2440),
    ('Eric', 'Rosen', 29, 'FM', 2435),
    ('Levy', 'Rozman', 28, 'IM', 2430),
    ('Anna', 'Rudolf', 35, 'WGM', 2425),
    ('Nemo', 'Zhou', 17, 'FM', 2420),
    ('Alejandro', 'Ramirez', 35, 'GM', 2415),

    -- Club Level Strong Players
    ('Thomas', 'Weber', 25, 'CM', 2350),
    ('Sofia', 'Martinez', 22, 'WCM', 2325),
    ('Viktor', 'Korchnoi Jr', 28, 'FM', 2310),
    ('Laura', 'Chen', 20, 'WFM', 2300),
    ('Igor', 'Smirnov', 31, 'NM', 2280),
    ('Maria', 'Schmidt', 24, 'WNM', 2250)

) AS p(First_Name, Last_Name, Age, Title_Code, ELO_Rating)
JOIN Title t ON t.Title_Code = p.Title_Code;

-- Populate Country table with standard data
INSERT INTO Country (Name, ISO_Code, Region) VALUES
-- Europe
('Albania', 'ALB', 'Europe'),
('Armenia', 'ARM', 'Europe'),
('Austria', 'AUT', 'Europe'),
('Azerbaijan', 'AZE', 'Europe'),
('Belarus', 'BLR', 'Europe'),
('Belgium', 'BEL', 'Europe'),
('Bosnia and Herzegovina', 'BIH', 'Europe'),
('Bulgaria', 'BGR', 'Europe'),
('Croatia', 'HRV', 'Europe'),
('Czech Republic', 'CZE', 'Europe'),
('Denmark', 'DNK', 'Europe'),
('Estonia', 'EST', 'Europe'),
('Finland', 'FIN', 'Europe'),
('France', 'FRA', 'Europe'),
('Georgia', 'GEO', 'Europe'),
('Germany', 'DEU', 'Europe'),
('Greece', 'GRC', 'Europe'),
('Hungary', 'HUN', 'Europe'),
('Iceland', 'ISL', 'Europe'),
('Ireland', 'IRL', 'Europe'),
('Italy', 'ITA', 'Europe'),
('Latvia', 'LVA', 'Europe'),
('Lithuania', 'LTU', 'Europe'),
('Luxembourg', 'LUX', 'Europe'),
('Malta', 'MLT', 'Europe'),
('Moldova', 'MDA', 'Europe'),
('Monaco', 'MCO', 'Europe'),
('Montenegro', 'MNE', 'Europe'),
('Netherlands', 'NLD', 'Europe'),
('North Macedonia', 'MKD', 'Europe'),
('Norway', 'NOR', 'Europe'),
('Poland', 'POL', 'Europe'),
('Portugal', 'PRT', 'Europe'),
('Romania', 'ROU', 'Europe'),
('Russia', 'RUS', 'Europe'),
('Serbia', 'SRB', 'Europe'),
('Slovakia', 'SVK', 'Europe'),
('Slovenia', 'SVN', 'Europe'),
('Spain', 'ESP', 'Europe'),
('Sweden', 'SWE', 'Europe'),
('Switzerland', 'CHE', 'Europe'),
('Ukraine', 'UKR', 'Europe'),
('United Kingdom', 'GBR', 'Europe'),

-- Asia
('Afghanistan', 'AFG', 'Asia'),
('Bangladesh', 'BGD', 'Asia'),
('Bhutan', 'BTN', 'Asia'),
('Cambodia', 'KHM', 'Asia'),
('China', 'CHN', 'Asia'),
('India', 'IND', 'Asia'),
('Indonesia', 'IDN', 'Asia'),
('Iran', 'IRN', 'Asia'),
('Iraq', 'IRQ', 'Asia'),
('Israel', 'ISR', 'Asia'),
('Japan', 'JPN', 'Asia'),
('Kazakhstan', 'KAZ', 'Asia'),
('Kuwait', 'KWT', 'Asia'),
('Kyrgyzstan', 'KGZ', 'Asia'),
('Laos', 'LAO', 'Asia'),
('Lebanon', 'LBN', 'Asia'),
('Malaysia', 'MYS', 'Asia'),
('Mongolia', 'MNG', 'Asia'),
('Myanmar', 'MMR', 'Asia'),
('Nepal', 'NPL', 'Asia'),
('North Korea', 'PRK', 'Asia'),
('Oman', 'OMN', 'Asia'),
('Pakistan', 'PAK', 'Asia'),
('Philippines', 'PHL', 'Asia'),
('Qatar', 'QAT', 'Asia'),
('Saudi Arabia', 'SAU', 'Asia'),
('Singapore', 'SGP', 'Asia'),
('South Korea', 'KOR', 'Asia'),
('Sri Lanka', 'LKA', 'Asia'),
('Syria', 'SYR', 'Asia'),
('Taiwan', 'TWN', 'Asia'),
('Tajikistan', 'TJK', 'Asia'),
('Thailand', 'THA', 'Asia'),
('Turkey', 'TUR', 'Asia'),
('Turkmenistan', 'TKM', 'Asia'),
('United Arab Emirates', 'ARE', 'Asia'),
('Uzbekistan', 'UZB', 'Asia'),
('Vietnam', 'VNM', 'Asia'),
('Yemen', 'YEM', 'Asia'),

-- Americas
('Argentina', 'ARG', 'Americas'),
('Bahamas', 'BHS', 'Americas'),
('Barbados', 'BRB', 'Americas'),
('Belize', 'BLZ', 'Americas'),
('Bolivia', 'BOL', 'Americas'),
('Brazil', 'BRA', 'Americas'),
('Canada', 'CAN', 'Americas'),
('Chile', 'CHL', 'Americas'),
('Colombia', 'COL', 'Americas'),
('Costa Rica', 'CRI', 'Americas'),
('Cuba', 'CUB', 'Americas'),
('Dominican Republic', 'DOM', 'Americas'),
('Ecuador', 'ECU', 'Americas'),
('El Salvador', 'SLV', 'Americas'),
('Guatemala', 'GTM', 'Americas'),
('Guyana', 'GUY', 'Americas'),
('Haiti', 'HTI', 'Americas'),
('Honduras', 'HND', 'Americas'),
('Jamaica', 'JAM', 'Americas'),
('Mexico', 'MEX', 'Americas'),
('Nicaragua', 'NIC', 'Americas'),
('Panama', 'PAN', 'Americas'),
('Paraguay', 'PRY', 'Americas'),
('Peru', 'PER', 'Americas'),
('Suriname', 'SUR', 'Americas'),
('Trinidad and Tobago', 'TTO', 'Americas'),
('United States', 'USA', 'Americas'),
('Uruguay', 'URY', 'Americas'),
('Venezuela', 'VEN', 'Americas'),

-- Africa
('Algeria', 'DZA', 'Africa'),
('Angola', 'AGO', 'Africa'),
('Benin', 'BEN', 'Africa'),
('Botswana', 'BWA', 'Africa'),
('Burkina Faso', 'BFA', 'Africa'),
('Burundi', 'BDI', 'Africa'),
('Cameroon', 'CMR', 'Africa'),
('Cape Verde', 'CPV', 'Africa'),
('Central African Republic', 'CAF', 'Africa'),
('Chad', 'TCD', 'Africa'),
('Comoros', 'COM', 'Africa'),
('Congo', 'COG', 'Africa'),
('Democratic Republic of the Congo', 'COD', 'Africa'),
('Djibouti', 'DJI', 'Africa'),
('Egypt', 'EGY', 'Africa'),
('Equatorial Guinea', 'GNQ', 'Africa'),
('Eritrea', 'ERI', 'Africa'),
('Ethiopia', 'ETH', 'Africa'),
('Gabon', 'GAB', 'Africa'),
('Gambia', 'GMB', 'Africa'),
('Ghana', 'GHA', 'Africa'),
('Guinea', 'GIN', 'Africa'),
('Guinea-Bissau', 'GNB', 'Africa'),
('Ivory Coast', 'CIV', 'Africa'),
('Kenya', 'KEN', 'Africa'),
('Lesotho', 'LSO', 'Africa'),
('Liberia', 'LBR', 'Africa'),
('Libya', 'LBY', 'Africa'),
('Madagascar', 'MDG', 'Africa'),
('Malawi', 'MWI', 'Africa'),
('Mali', 'MLI', 'Africa'),
('Mauritania', 'MRT', 'Africa'),
('Mauritius', 'MUS', 'Africa'),
('Morocco', 'MAR', 'Africa'),
('Mozambique', 'MOZ', 'Africa'),
('Namibia', 'NAM', 'Africa'),
('Niger', 'NER', 'Africa'),
('Nigeria', 'NGA', 'Africa'),
('Rwanda', 'RWA', 'Africa'),
('Senegal', 'SEN', 'Africa'),
('Seychelles', 'SYC', 'Africa'),
('Sierra Leone', 'SLE', 'Africa'),
('Somalia', 'SOM', 'Africa'),
('South Africa', 'ZAF', 'Africa'),
('South Sudan', 'SSD', 'Africa'),
('Sudan', 'SDN', 'Africa'),
('Swaziland', 'SWZ', 'Africa'),
('Tanzania', 'TZA', 'Africa'),
('Togo', 'TGO', 'Africa'),
('Tunisia', 'TUN', 'Africa'),
('Uganda', 'UGA', 'Africa'),
('Zambia', 'ZMB', 'Africa'),
('Zimbabwe', 'ZWE', 'Africa'),

-- Oceania
('Australia', 'AUS', 'Oceania'),
('Fiji', 'FJI', 'Oceania'),
('Kiribati', 'KIR', 'Oceania'),
('Marshall Islands', 'MHL', 'Oceania'),
('Micronesia', 'FSM', 'Oceania'),
('Nauru', 'NRU', 'Oceania'),
('New Zealand', 'NZL', 'Oceania'),
('Palau', 'PLW', 'Oceania'),
('Papua New Guinea', 'PNG', 'Oceania'),
('Samoa', 'WSM', 'Oceania'),
('Solomon Islands', 'SLB', 'Oceania'),
('Tonga', 'TON', 'Oceania'),
('Tuvalu', 'TUV', 'Oceania'),
('Vanuatu', 'VUT', 'Oceania');

-- Insert Player-Country relationships
INSERT INTO Player_Country (Player_Id, Country_Id, Start_Date)
SELECT p.Player_Id, c.Country_Id, '2024-01-01'  -- Using a default start date
FROM Player p, Country c
WHERE (
    -- Mapping each player to their country
    (p.First_Name = 'Magnus' AND p.Last_Name = 'Carlsen' AND c.Name = 'Norway') OR
    (p.First_Name = 'Fabiano' AND p.Last_Name = 'Caruana' AND c.Name = 'United States') OR
    (p.First_Name = 'Hikaru' AND p.Last_Name = 'Nakamura' AND c.Name = 'United States') OR
    (p.First_Name = 'Arjun' AND p.Last_Name = 'Erigaisi' AND c.Name = 'India') OR
    (p.First_Name = 'Gukesh' AND p.Last_Name = 'Dommaraju' AND c.Name = 'India') OR
    (p.First_Name = 'Nodirbek' AND p.Last_Name = 'Abdusattorov' AND c.Name = 'Uzbekistan') OR
    (p.First_Name = 'Alireza' AND p.Last_Name = 'Firouzja' AND c.Name = 'France') OR
    (p.First_Name = 'Ian' AND p.Last_Name = 'Nepomniachtchi' AND c.Name = 'Russia') OR
    (p.First_Name = 'Yi' AND p.Last_Name = 'Wei' AND c.Name = 'China') OR
    (p.First_Name = 'Viswanathan' AND p.Last_Name = 'Anand' AND c.Name = 'India') OR
    (p.First_Name = 'Levon' AND p.Last_Name = 'Aronian' AND c.Name = 'Armenia') OR
    (p.First_Name = 'Wesley' AND p.Last_Name = 'So' AND c.Name = 'United States') OR
    (p.First_Name = 'Sergey' AND p.Last_Name = 'Karjakin' AND c.Name = 'Russia') OR
    (p.First_Name = 'Alexander' AND p.Last_Name = 'Grischuk' AND c.Name = 'Russia') OR
    (p.First_Name = 'Dominguez' AND p.Last_Name = 'Perez' AND c.Name = 'United States') OR
    (p.First_Name = 'Praggnanandhaa' AND c.Name = 'India') OR
    (p.First_Name = 'Jan-Krzysztof' AND p.Last_Name = 'Duda' AND c.Name = 'Poland') OR
    (p.First_Name = 'Quang Liem' AND p.Last_Name = 'Le' AND c.Name = 'Vietnam') OR
    (p.First_Name = 'Liren' AND p.Last_Name = 'Ding' AND c.Name = 'China') OR
    (p.First_Name = 'Hans' AND p.Last_Name = 'Niemann' AND c.Name = 'United States') OR
    (p.First_Name = 'Vincent' AND p.Last_Name = 'Keymer' AND c.Name = 'Germany') OR
    (p.First_Name = 'Maxime' AND p.Last_Name = 'Vachier-Lagrave' AND c.Name = 'France') OR
    (p.First_Name = 'Shakhriyar' AND p.Last_Name = 'Mamedyarov' AND c.Name = 'Azerbaijan') OR
    (p.First_Name = 'Anish' AND p.Last_Name = 'Giri' AND c.Name = 'Netherlands') OR
    -- Strong GMs
    (p.First_Name = 'Peter' AND p.Last_Name = 'Svidler' AND c.Name = 'Russia') OR
    (p.First_Name = 'Boris' AND p.Last_Name = 'Gelfand' AND c.Name = 'Israel') OR
    (p.First_Name = 'Pentala' AND p.Last_Name = 'Harikrishna' AND c.Name = 'India') OR
    (p.First_Name = 'Dmitry' AND p.Last_Name = 'Andreikin' AND c.Name = 'Russia') OR
    (p.First_Name = 'Vladimir' AND p.Last_Name = 'Kramnik' AND c.Name = 'Russia') OR
    (p.First_Name = 'Sam' AND p.Last_Name = 'Shankland' AND c.Name = 'United States') OR
    (p.First_Name = 'David' AND p.Last_Name = 'Navara' AND c.Name = 'Czech Republic') OR
    (p.First_Name = 'Bu' AND p.Last_Name = 'Xiangzhi' AND c.Name = 'China') OR
    (p.First_Name = 'Radoslaw' AND p.Last_Name = 'Wojtaszek' AND c.Name = 'Poland') OR
    (p.First_Name = 'Francisco' AND p.Last_Name = 'Vallejo Pons' AND c.Name = 'Spain') OR
    -- Top Female Players
    (p.First_Name = 'Hou' AND p.Last_Name = 'Yifan' AND c.Name = 'China') OR
    (p.First_Name = 'Ju' AND p.Last_Name = 'Wenjun' AND c.Name = 'China') OR
    (p.First_Name = 'Aleksandra' AND p.Last_Name = 'Goryachkina' AND c.Name = 'Russia') OR
    (p.First_Name = 'Koneru' AND p.Last_Name = 'Humpy' AND c.Name = 'India') OR
    (p.First_Name = 'Anna' AND p.Last_Name = 'Muzychuk' AND c.Name = 'Ukraine') OR
    (p.First_Name = 'Kateryna' AND p.Last_Name = 'Lagno' AND c.Name = 'Russia') OR
    (p.First_Name = 'Mariya' AND p.Last_Name = 'Muzychuk' AND c.Name = 'Ukraine') OR
    (p.First_Name = 'Alexandra' AND p.Last_Name = 'Kosteniuk' AND c.Name = 'Switzerland') OR
    (p.First_Name = 'Tan' AND p.Last_Name = 'Zhongyi' AND c.Name = 'China') OR
    (p.First_Name = 'Lei' AND p.Last_Name = 'Tingjie' AND c.Name = 'China') OR
    -- Strong IMs and Rising Stars
    (p.First_Name = 'Nihal' AND p.Last_Name = 'Sarin' AND c.Name = 'India') OR
    (p.First_Name = 'Raunak' AND p.Last_Name = 'Sadhwani' AND c.Name = 'India') OR
    (p.First_Name = 'Christopher' AND p.Last_Name = 'Yoo' AND c.Name = 'United States') OR
    (p.First_Name = 'Abhimanyu' AND p.Last_Name = 'Mishra' AND c.Name = 'United States') OR
    (p.First_Name = 'Marc' AND p.Last_Name = 'Andria Maurizzi' AND c.Name = 'France') OR
    (p.First_Name = 'Jonas' AND p.Last_Name = 'Bjerre' AND c.Name = 'Denmark') OR
    (p.First_Name = 'Leon' AND p.Last_Name = 'Mendonca' AND c.Name = 'India') OR
    -- Female IMs and WGMs
    (p.First_Name = 'Bibisara' AND p.Last_Name = 'Assaubayeva' AND c.Name = 'Kazakhstan') OR
    (p.First_Name = 'Zhansaya' AND p.Last_Name = 'Abdumalik' AND c.Name = 'Kazakhstan') OR
    (p.First_Name = 'Dinara' AND p.Last_Name = 'Wagner' AND c.Name = 'Germany') OR
    (p.First_Name = 'Nurgyul' AND p.Last_Name = 'Salimova' AND c.Name = 'Bulgaria') OR
    (p.First_Name = 'Zhu' AND p.Last_Name = 'Jiner' AND c.Name = 'China') OR
    -- National Masters and FMs
    (p.First_Name = 'Maximillian' AND p.Last_Name = 'Lu' AND c.Name = 'United States') OR
    (p.First_Name = 'Andrew' AND p.Last_Name = 'Tang' AND c.Name = 'United States') OR
    (p.First_Name = 'Daniel' AND p.Last_Name = 'Naroditsky' AND c.Name = 'United States') OR
    (p.First_Name = 'Eric' AND p.Last_Name = 'Rosen' AND c.Name = 'United States') OR
    (p.First_Name = 'Levy' AND p.Last_Name = 'Rozman' AND c.Name = 'United States') OR
    (p.First_Name = 'Anna' AND p.Last_Name = 'Rudolf' AND c.Name = 'Hungary') OR
    (p.First_Name = 'Nemo' AND p.Last_Name = 'Zhou' AND c.Name = 'China') OR
    (p.First_Name = 'Alejandro' AND p.Last_Name = 'Ramirez' AND c.Name = 'Costa Rica') OR
    -- Club Level Strong Players
    (p.First_Name = 'Thomas' AND p.Last_Name = 'Weber' AND c.Name = 'Germany') OR
    (p.First_Name = 'Sofia' AND p.Last_Name = 'Martinez' AND c.Name = 'Spain') OR
    (p.First_Name = 'Viktor' AND p.Last_Name = 'Korchnoi Jr' AND c.Name = 'Switzerland') OR
    (p.First_Name = 'Laura' AND p.Last_Name = 'Chen' AND c.Name = 'China') OR
    (p.First_Name = 'Igor' AND p.Last_Name = 'Smirnov' AND c.Name = 'Russia') OR
    (p.First_Name = 'Maria' AND p.Last_Name = 'Schmidt' AND c.Name = 'Germany')
);

INSERT INTO Opening (Name, ECO_Code, Agressiveness)
VALUES
-- A Series (Flank Openings)
('English Opening', 'A10', FALSE),
('English, Caro-Kann Defensive System', 'A11', FALSE),
('English, Réti System', 'A12', FALSE),
('English, Agincourt Defense', 'A13', FALSE),
('English, Neo-Catalan Declined', 'A14', FALSE),
('English, Anglo-Indian Defense', 'A15', FALSE),
('English, Anglo-Grünfeld Defense', 'A16', TRUE),
('English, Queens Indian Formation', 'A17', FALSE),
('English, Mikenas-Carls Variation', 'A18', TRUE),
('English, Sicilian Defense', 'A20', TRUE),
('English, Bremen System', 'A21', FALSE),
('English, Bremen, Reverse Dragon', 'A22', TRUE),
('English, Bremen, Four Knights', 'A23', FALSE),
('English, Bremen, Closed System', 'A24', FALSE),
('English, Sicilian Reversed', 'A25', TRUE),
('English, Closed System', 'A30', FALSE),
('English, Symmetrical Variation', 'A31', FALSE),
('English, Symmetrical, Hedgehog System', 'A32', FALSE),
('English, Symmetrical, Anti-Benoni', 'A33', TRUE),
('English, Symmetrical, Three Knights', 'A34', FALSE),
('English, Symmetrical, Four Knights', 'A35', FALSE),
('English, Ultra-Symmetrical Variation', 'A36', FALSE),
('English, Three Knights System', 'A37', FALSE),
('English, Symmetrical, Main Line', 'A38', FALSE),
('English, Symmetrical, Main Line with d4', 'A39', TRUE),
('Queens Pawn, Polish Defense', 'A40', TRUE),
('Queens Pawn, Modern Defense', 'A41', TRUE),
('Modern Defense, Averbakh System', 'A42', TRUE),
('Old Benoni Defense', 'A43', TRUE),
('Old Benoni, Czech Variation', 'A44', TRUE),
('Queens Pawn Game', 'A45', FALSE),
('Queens Pawn, Torre Attack', 'A46', TRUE),
('Queens Indian Defense', 'A47', FALSE),
('East Indian Defense', 'A48', FALSE),
('Indian Game, Kings Knight Variation', 'A49', FALSE),
('Queens Pawn Game', 'A50', FALSE),
('Budapest Gambit', 'A51', TRUE),
('Budapest Gambit Accepted', 'A52', TRUE),
('Old Indian Defense', 'A53', FALSE),
('Old Indian, Ukrainian Variation', 'A54', FALSE),
('Old Indian, Main Line', 'A55', FALSE),
('Benoni Defense', 'A56', TRUE),
('Benko Gambit', 'A57', TRUE),
('Benko Gambit Accepted', 'A58', TRUE),
('Benko Gambit, Main Line', 'A59', TRUE),
('Modern Defense', 'A60', TRUE),
('Modern Defense, Anti-Modern Variation', 'A61', TRUE),
('Modern Defense, Fianchetto Variation', 'A62', TRUE),
('Modern Defense, Main Line', 'A63', TRUE),
('Benoni Defense, Modern Variation', 'A64', TRUE),
('Modern Benoni', 'A65', TRUE),
('Modern Benoni, Main Line', 'A66', TRUE),
('Modern Benoni, Taimanov Variation', 'A67', TRUE),
('Modern Benoni, Four Pawns Attack', 'A68', TRUE),
('Modern Benoni, Four Pawns Attack, Main Line', 'A69', TRUE),
('Modern Benoni, Classical', 'A70', TRUE),
('Modern Benoni, Classical, Main Line', 'A71', TRUE),
('Modern Benoni, Classical, Ne2', 'A72', TRUE),
('Modern Benoni, Classical, Main Line', 'A73', TRUE),
('Modern Benoni, Classical, Main Line', 'A74', TRUE),

-- B Series (Semi-Open Games)
('Modern Defense', 'B00', TRUE),
('Scandinavian Defense', 'B01', FALSE),
('Alekhines Defense', 'B02', TRUE),
('Alekhines Defense, Modern Variation', 'B03', TRUE),
('Alekhines Defense, Modern, Fianchetto Variation', 'B04', TRUE),
('Alekhines Defense, Modern, Main Line', 'B05', TRUE),
('Modern Defense, Robatsch Defense', 'B06', TRUE),
('Pirc Defense', 'B07', TRUE),
('Pirc, Classical (Two Knights) System', 'B08', TRUE),
('Pirc, Austrian Attack', 'B09', TRUE),
('Caro-Kann Defense', 'B10', FALSE),
('Caro-Kann, Two Knights, 3...Bg4', 'B11', FALSE),
('Caro-Kann Defense, Advance Variation', 'B12', FALSE),
('Caro-Kann, Exchange Variation', 'B13', FALSE),
('Caro-Kann, Panov-Botvinnik Attack', 'B14', TRUE),
('Caro-Kann, Tartakower (Nimzowitsch) Variation', 'B15', FALSE),
('Caro-Kann, Bronstein-Larsen Variation', 'B16', FALSE),
('Caro-Kann, Steinitz Variation', 'B17', FALSE),
('Caro-Kann, Classical Variation', 'B18', FALSE),
('Caro-Kann, Classical, Main Line', 'B19', FALSE),
('Sicilian Defense', 'B20', TRUE),
('Sicilian, Grand Prix Attack', 'B21', TRUE),
('Sicilian, Alapin Variation', 'B22', TRUE),
('Sicilian, Closed', 'B23', FALSE),
('Sicilian, Closed, Fianchetto Variation', 'B24', FALSE),
('Sicilian, Closed, 6.f4', 'B25', TRUE),
('Sicilian, Closed System', 'B26', FALSE),
('Sicilian, Dragon Variation', 'B27', TRUE),
('Sicilian, Dragon, Classical Variation', 'B28', TRUE),
('Sicilian, Nimzowitsch-Rubinstein Variation', 'B29', TRUE),
('Sicilian, Rossolimo Variation', 'B30', FALSE),
('Sicilian, Nimzowitsch-Rossolimo Attack', 'B31', FALSE),
('Sicilian, Löwenthal Variation', 'B32', TRUE),
('Sicilian, Sveshnikov Variation', 'B33', TRUE),
('Sicilian, Accelerated Dragon', 'B34', TRUE),
('Sicilian, Dragon, Modern Variation', 'B35', TRUE),
('Sicilian, Maróczy Bind', 'B36', FALSE),
('Sicilian, Accelerated Fianchetto', 'B37', TRUE),
('Sicilian, Maróczy Bind, Main Line', 'B38', FALSE),
('Sicilian, Maróczy Bind, Main Line', 'B39', FALSE),
('Sicilian, Kan Variation', 'B40', TRUE),
('Sicilian, Kan, Maróczy Bind', 'B41', FALSE),
('Sicilian, Kan, 5.Bd3', 'B42', TRUE),
('Sicilian, Kan, Modern Variation', 'B43', TRUE),
('Sicilian, Taimanov Variation', 'B44', TRUE),
('Sicilian, Taimanov, Main Line', 'B45', TRUE),
('Sicilian, Taimanov Variation', 'B46', TRUE),
('Sicilian, Taimanov, Bastrikov Variation', 'B47', TRUE),
('Sicilian, Taimanov Variation', 'B48', TRUE),
('Sicilian, Taimanov Variation', 'B49', TRUE),
('Sicilian, Dragon Variation', 'B50', TRUE),
('Sicilian, Canal-Sokolsky Attack', 'B51', TRUE),
('Sicilian, Canal-Sokolsky, Bronstein Variation', 'B52', TRUE),
('Sicilian, Chekhover Variation', 'B53', TRUE),
('Sicilian, Dragon, Classical Variation', 'B54', TRUE),
('Sicilian, Dragon, Classical, Main Line', 'B55', TRUE),
('Sicilian, Venice Attack', 'B56', TRUE),
('Sicilian, Dragon, Yugoslav Attack', 'B57', TRUE),
('Sicilian, Classical Variation', 'B58', TRUE),
('Sicilian, Boleslavsky Variation', 'B59', TRUE),
('Sicilian, Richter-Rauzer', 'B60', TRUE),
('Sicilian, Richter-Rauzer, Modern Variation', 'B61', TRUE),
('Sicilian, Richter-Rauzer, 6...e6', 'B62', TRUE),
('Sicilian, Richter-Rauzer Attack', 'B63', TRUE),
('Sicilian, Richter-Rauzer Attack', 'B64', TRUE),
('Sicilian, Richter-Rauzer Attack', 'B65', TRUE),
('Sicilian, Richter-Rauzer Attack', 'B66', TRUE),
('Sicilian, Richter-Rauzer Attack', 'B67', TRUE),
('Sicilian, Richter-Rauzer, Main Line', 'B68', TRUE),
('Sicilian, Richter-Rauzer, Main Line', 'B69', TRUE),

-- C Series (Open Games)
('Kings Pawn Opening', 'C00', TRUE),
('French Defense', 'C01', FALSE),
('French, Advance Variation', 'C02', FALSE),
('French, Tarrasch', 'C03', FALSE),
('French, Tarrasch, Guimard Main Line', 'C04', FALSE),
('French, Tarrasch, Closed Variation', 'C05', FALSE),
('French, Tarrasch, Closed, Main Line', 'C06', FALSE),
('French, Tarrasch, Open Variation', 'C07', TRUE),
('French, Tarrasch, Open, 4.ed ed', 'C08', TRUE),
('French, Tarrasch, Main Line', 'C09', FALSE),
('French, Paulsen Variation', 'C10', FALSE),
('French, Classical', 'C11', FALSE),
('French, McCutcheon Variation', 'C12', TRUE),
('French, Classical, Richter Attack', 'C13', TRUE),
('French, Classical, Steinitz Variation', 'C14', FALSE),
('French, Winawer Variation', 'C15', TRUE),
('French, Winawer, Main Line', 'C16', TRUE),
('French, Winawer, Advance Variation', 'C17', TRUE),
('French, Winawer, Advance Variation', 'C18', TRUE),
('French, Winawer, Advance, 6...Ne7', 'C19', TRUE),
('Kings Pawn Game', 'C20', TRUE),
('Center Game', 'C21', TRUE),
('Center Game Accepted', 'C22', TRUE),
('Bishops Opening', 'C23', FALSE),
('Bishops Opening, Berlin Defense', 'C24', FALSE),
('Vienna Game', 'C25', TRUE),
('Vienna Game, Classical Variation', 'C26', TRUE),
('Vienna Game, Frankenstein-Dracula Variation', 'C27', TRUE),
('Vienna Game, Main Line', 'C28', TRUE),
('Vienna Game, Main Line', 'C29', TRUE),
('Kings Gambit', 'C30', TRUE),
('Kings Gambit Declined', 'C31', TRUE),
('Kings Gambit Declined, Falkbeer Counter-Gambit', 'C32', TRUE),
('Kings Gambit Accepted', 'C33', TRUE),
('Kings Gambit Accepted, Fischer Defense', 'C34', TRUE),
('Kings Gambit Accepted, Cunningham Defense', 'C35', TRUE),
('Kings Gambit Accepted, Modern Defense', 'C36', TRUE),
('Kings Gambit Accepted, Classical Variation', 'C37', TRUE),
('Kings Gambit Accepted, Classical, Main Line', 'C38', TRUE),
('Kings Gambit Accepted, Classical, Main Line', 'C39', TRUE),
('Queens Pawn Game', 'C40', FALSE),
('Philidor Defense', 'C41', FALSE),
('Petrov Defense', 'C42', FALSE),
('Petrov, Modern Attack', 'C43', TRUE),
('Kings Pawn Game', 'C44', TRUE),
('Scotch Game', 'C45', TRUE),
('Three Knights Game', 'C46', FALSE),
('Four Knights Game', 'C47', FALSE),
('Four Knights, Spanish Variation', 'C48', FALSE),
('Four Knights, Double Ruy Lopez', 'C49', FALSE),
('Italian Game', 'C50', TRUE),
('Evans Gambit', 'C51', TRUE),
('Evans Gambit, Main Line', 'C52', TRUE),
('Giuoco Piano', 'C53', FALSE),
('Giuoco Piano, Main Line', 'C54', FALSE),
('Two Knights Defense', 'C55', TRUE),
('Two Knights Defense, Main Line', 'C56', TRUE),
('Two Knights Defense, Ulvestad Variation', 'C57', TRUE),
('Two Knights Defense, Modern Variation', 'C58', TRUE),
('Two Knights Defense, Modern, Main Line', 'C59', TRUE),
('Ruy Lopez', 'C60', TRUE),
('Ruy Lopez, Birds Defense', 'C61', TRUE),
('Ruy Lopez, Old Steinitz Defense', 'C62', FALSE),
('Ruy Lopez, Schliemann Defense', 'C63', TRUE),
('Ruy Lopez, Classical Defense', 'C64', FALSE),
('Ruy Lopez, Berlin Defense', 'C65', FALSE),
('Ruy Lopez, Berlin Defense, Main Line', 'C66', FALSE),
('Ruy Lopez, Berlin Defense, Rio de Janeiro Variation', 'C67', FALSE),
('Ruy Lopez, Exchange Variation', 'C68', FALSE),
('Ruy Lopez, Exchange, Main Line', 'C69', FALSE),
('Ruy Lopez, Modern Steinitz Defense', 'C70', FALSE),
('Ruy Lopez, Modern Steinitz, Main Line', 'C71', FALSE),
('Ruy Lopez, Modern Steinitz, 5.O-O', 'C72', FALSE),
('Ruy Lopez, Modern Steinitz, Siesta Variation', 'C73', FALSE),
('Ruy Lopez, Modern Steinitz, Siesta, Main Line', 'C74', FALSE),
('Ruy Lopez, Modern Steinitz, Siesta, Main Line', 'C75', FALSE),
('Ruy Lopez, Modern Steinitz, Main Line', 'C76', FALSE),
('Ruy Lopez, Morphy Defense', 'C77', TRUE),
('Ruy Lopez, Morphy Defense, Main Line', 'C78', TRUE),
('Ruy Lopez, Closed (Main Line)', 'C79', FALSE),
-- D Series (Closed Games)
('Queens Gambit Declined', 'D00', FALSE),
('Richter-Veresov Attack', 'D01', TRUE),
('Queens Pawn Game, London System', 'D02', FALSE),
('Queens Pawn Game, Torre Attack', 'D03', FALSE),
('Queens Pawn Game, Colle System', 'D04', FALSE),
('Queens Pawn Game, Zukertort Attack', 'D05', FALSE),
('Queens Gambit', 'D06', FALSE),
('Queens Gambit Declined, Chigorin Defense', 'D07', TRUE),
('Queens Gambit Declined, Albin Counter Gambit', 'D08', TRUE),
('Queens Gambit Declined, Albin Counter Gambit, 5.g3', 'D09', TRUE),
('Queens Gambit Declined Slav Defense', 'D10', FALSE),
('Queens Gambit Declined Slav, Modern Line', 'D11', FALSE),
('Queens Gambit Declined Slav, 4.e3 Bf5', 'D12', FALSE),
('Queens Gambit Declined Slav, Exchange Variation', 'D13', FALSE),
('Queens Gambit Declined Slav, Exchange, Main Line', 'D14', FALSE),
('Queens Gambit Declined Slav, 4.Nc3', 'D15', FALSE),
('Queens Gambit Declined Slav, Smyslov Variation', 'D16', FALSE),
('Queens Gambit Declined Slav, Czech Defense', 'D17', FALSE),
('Queens Gambit Declined Slav, Dutch Variation', 'D18', FALSE),
('Queens Gambit Declined Slav, Dutch, Main Line', 'D19', FALSE),
('Queens Gambit Accepted', 'D20', TRUE),
('Queens Gambit Accepted, 3.Nf3', 'D21', TRUE),
('Queens Gambit Accepted, Alekhine Defense', 'D22', TRUE),
('Queens Gambit Accepted, Accelerated Development', 'D23', TRUE),
('Queens Gambit Accepted, 4.Nc3', 'D24', TRUE),
('Queens Gambit Accepted, Main Line', 'D25', TRUE),
('Queens Gambit Accepted, Classical Defense', 'D26', FALSE),
('Queens Gambit Accepted, Classical, Main Line', 'D27', FALSE),
('Queens Gambit Accepted, Classical, Flohr Variation', 'D28', FALSE),
('Queens Gambit Accepted, Classical, Vienna Variation', 'D29', TRUE),
('Queens Gambit Declined', 'D30', FALSE),
('Queens Gambit Declined, Queens Knight Variation', 'D31', FALSE),
('Queens Gambit Declined, Tarrasch Defense', 'D32', FALSE),
('Queens Gambit Declined, Tarrasch, Schlechter Variation', 'D33', FALSE),
('Queens Gambit Declined, Tarrasch, Prague Variation', 'D34', FALSE),
('Queens Gambit Declined, Tarrasch, Main Line', 'D35', FALSE),
('Queens Gambit Declined, Exchange Variation', 'D36', FALSE),
('Queens Gambit Declined, Exchange, Main Line', 'D37', FALSE),
('Queens Gambit Declined, Ragozin Defense', 'D38', TRUE),
('Queens Gambit Declined, Ragozin, Vienna Variation', 'D39', TRUE),
('Queens Gambit Declined, Semi-Tarrasch', 'D40', FALSE),
('Queens Gambit Declined, Semi-Tarrasch, 5.cd', 'D41', FALSE),
('Queens Gambit Declined, Semi-Tarrasch, Main Line', 'D42', FALSE),
('Queens Gambit Declined, Semi-Tarrasch with Bg5', 'D43', FALSE),
('Queens Gambit Declined Semi-Slav', 'D44', FALSE),
('Queens Gambit Declined Semi-Slav, 5.e3', 'D45', FALSE),
('Queens Gambit Declined Semi-Slav, 6.Bd3', 'D46', FALSE),
('Queens Gambit Declined Semi-Slav, Meran', 'D47', TRUE),
('Queens Gambit Declined Semi-Slav, Meran, 8...a6', 'D48', TRUE),
('Queens Gambit Declined Semi-Slav, Meran, Main Line', 'D49', TRUE),
('Queens Gambit Declined, 4.Bg5', 'D50', FALSE),
('Queens Gambit Declined, 4.Bg5 Nbd7', 'D51', FALSE),
('Queens Gambit Declined, Cambridge Springs Defense', 'D52', TRUE),
('Queens Gambit Declined, 4.Bg5 Be7', 'D53', FALSE),
('Queens Gambit Declined, Neo-Orthodox Variation', 'D54', FALSE),
('Queens Gambit Declined, Neo-Orthodox, Main Line', 'D55', FALSE),
('Queens Gambit Declined, Lasker Defense', 'D56', FALSE),
('Queens Gambit Declined, Lasker, Main Line', 'D57', FALSE),
('Queens Gambit Declined, Tartakower Defense', 'D58', FALSE),
('Queens Gambit Declined, Tartakower, Main Line', 'D59', FALSE),
('Queens Gambit Declined, Orthodox Defense', 'D60', FALSE),
('Queens Gambit Declined, Orthodox, Rubinstein Variation', 'D61', FALSE),
('Queens Gambit Declined, Orthodox, 7.Qc2', 'D62', FALSE),
('Queens Gambit Declined, Orthodox, 7.Rc1', 'D63', FALSE),
('Queens Gambit Declined, Orthodox, Rubinstein Attack', 'D64', FALSE),
('Queens Gambit Declined, Orthodox, Rubinstein, Main Line', 'D65', FALSE),
('Queens Gambit Declined, Orthodox Defense, Main Line', 'D66', FALSE),
('Queens Gambit Declined, Orthodox, Bd3 Line', 'D67', FALSE),
('Queens Gambit Declined, Orthodox, Classical Variation', 'D68', FALSE),
('Queens Gambit Declined, Orthodox, Classical, Main Line', 'D69', FALSE),
('Neo-Grünfeld Defense', 'D70', TRUE),
('Neo-Grünfeld, 5.cd', 'D71', TRUE),
('Neo-Grünfeld, 5.cd, Main Line', 'D72', TRUE),
('Neo-Grünfeld, 5.Nf3', 'D73', TRUE),
('Neo-Grünfeld, 6.cd Nxd5, 7.O-O', 'D74', TRUE),
('Neo-Grünfeld, 6.cd Nxd5, 7.O-O c5, 8.Nc3', 'D75', TRUE),
('Neo-Grünfeld, 6.cd Nxd5, 7.O-O Nb6', 'D76', TRUE),
('Neo-Grünfeld, 6.O-O c6', 'D77', TRUE),
('Neo-Grünfeld, Classical Variation', 'D78', TRUE),
('Neo-Grünfeld, Ultra-delayed Exchange', 'D79', TRUE),
('Grünfeld Defense', 'D80', TRUE),
('Grünfeld, Russian Variation', 'D81', TRUE),
('Grünfeld, 4.Bf4', 'D82', TRUE),
('Grünfeld, Grünfeld Gambit', 'D83', TRUE),
('Grünfeld, Grünfeld Gambit Accepted', 'D84', TRUE),
('Grünfeld, Exchange Variation', 'D85', TRUE),
('Grünfeld, Exchange, Classical Variation', 'D86', TRUE),
('Grünfeld, Exchange, Spassky Variation', 'D87', TRUE),
('Grünfeld, Spassky, Main Line, 10...cd, 11.cd', 'D88', TRUE),
('Grünfeld, Spassky, Main Line, 13.Bd3', 'D89', TRUE),
('Grünfeld, Three Knights Variation', 'D90', TRUE),
('Grünfeld, Three Knights, 5.Nf3', 'D91', TRUE),
('Grünfeld, 5.Bf4', 'D92', TRUE),
('Grünfeld, with Bf4 & e3', 'D93', TRUE),
('Grünfeld, 5.e3', 'D94', TRUE),
('Grünfeld with e3 & Qb3', 'D95', TRUE),
('Grünfeld, Russian Variation', 'D96', TRUE),
('Grünfeld, Russian, Main Line', 'D97', TRUE),
('Grünfeld, Russian, Smyslov Variation', 'D98', TRUE),
('Grünfeld Defense, Main Line', 'D99', TRUE),

-- E Series (Indian Defenses)
('Queens Pawn Game', 'E00', FALSE),
('Catalan Opening', 'E01', FALSE),
('Catalan Opening, Open Defense', 'E02', FALSE),
('Catalan Opening, Open, 5.Qa4', 'E03', FALSE),
('Catalan Opening, Open, 5.Nf3', 'E04', FALSE),
('Catalan Opening, Classical Line', 'E05', FALSE),
('Catalan Opening, Closed', 'E06', FALSE),
('Catalan Opening, Closed, 6...Nbd7', 'E07', FALSE),
('Catalan Opening, Closed, 7.Qc2', 'E08', FALSE),
('Catalan Opening, Closed, Main Line', 'E09', FALSE),
('Queens Pawn Game, Blumenfeld Counter Gambit', 'E10', TRUE),
('Bogo-Indian Defense', 'E11', FALSE),
('Queens Indian Defense', 'E12', FALSE),
('Queens Indian, 4.Nc3, Main Line', 'E13', FALSE),
('Queens Indian, 4.e3', 'E14', FALSE),
('Queens Indian, 4.g3', 'E15', FALSE),
('Queens Indian, Capablanca Variation', 'E16', FALSE),
('Queens Indian, 5.Bg2 Be7', 'E17', FALSE),
('Queens Indian, Old Main Line', 'E18', FALSE),
('Queens Indian, Main Line', 'E19', FALSE),
('Nimzo-Indian Defense', 'E20', FALSE),
('Nimzo-Indian, Three Knights', 'E21', FALSE),
('Nimzo-Indian, Spielmann Variation', 'E22', FALSE),
('Nimzo-Indian, Spielmann, 4...c5, 5.dc Nc6', 'E23', FALSE),
('Nimzo-Indian, Sämisch Variation', 'E24', TRUE),
('Nimzo-Indian, Sämisch, Main Line', 'E25', TRUE),
('Nimzo-Indian, Sämisch, 5...O-O', 'E26', TRUE),
('Nimzo-Indian, Sämisch, 5...Nc6', 'E27', TRUE),
('Nimzo-Indian, Sämisch, Main Line', 'E28', TRUE),
('Nimzo-Indian, Sämisch, Main Line', 'E29', TRUE),
('Nimzo-Indian, Leningrad', 'E30', FALSE),
('Nimzo-Indian, Leningrad, Main Line', 'E31', FALSE),
('Nimzo-Indian, Classical', 'E32', FALSE),
('Nimzo-Indian, Classical, Main Line', 'E33', FALSE),
('Nimzo-Indian, Classical, Noa Variation', 'E34', FALSE),
('Nimzo-Indian, Classical, Noa, Main Line', 'E35', FALSE),
('Nimzo-Indian, Classical, Botvinnik', 'E36', FALSE),
('Nimzo-Indian, Classical, Botvinnik, Main Line', 'E37', FALSE),
('Nimzo-Indian, Classical, 4...c5', 'E38', FALSE),
('Nimzo-Indian, Classical, Pirc Variation', 'E39', FALSE),
('Nimzo-Indian, 4.e3', 'E40', FALSE),
('Nimzo-Indian, 4.e3 c5', 'E41', FALSE),
('Nimzo-Indian, Hubner Variation', 'E42', FALSE),
('Nimzo-Indian, Fischer Variation', 'E43', FALSE),
('Nimzo-Indian, Fischer Variation, Main Line', 'E44', FALSE),
('Nimzo-Indian, 4.e3, Bronstein (Byrne) Variation', 'E45', FALSE),
('Nimzo-Indian, 4.e3 O-O', 'E46', FALSE),
('Nimzo-Indian, 4.e3 b6', 'E47', FALSE),
('Nimzo-Indian, 4.e3 O-O 5.Bd3', 'E48', FALSE),
('Nimzo-Indian, 4.e3, Main Line', 'E49', FALSE),
('Kings Indian Defense', 'E60', TRUE),
('Kings Indian, 3.Nc3', 'E61', TRUE),
('Kings Indian, Fianchetto', 'E62', TRUE),
('Kings Indian, Fianchetto, Panno Variation', 'E63', TRUE),
('Kings Indian, Fianchetto, Yugoslav System', 'E64', TRUE),
('Kings Indian, Fianchetto, Yugoslav, 7.O-O', 'E65', TRUE),
('Kings Indian, Fianchetto, Yugoslav Panno', 'E66', TRUE),
('Kings Indian, Fianchetto with ...Nd7', 'E67', TRUE),
('Kings Indian, Fianchetto, Classical Variation', 'E68', TRUE),
('Kings Indian, Fianchetto, Classical Main Line', 'E69', TRUE),
('Kings Indian, 4.e4', 'E70', TRUE),
('Kings Indian, Makagonov System (5.h3)', 'E71', TRUE),
('Kings Indian with e4 & g3', 'E72', TRUE),
('Kings Indian, 5.Be2', 'E73', TRUE),
('Kings Indian, Averbakh, 6...c5', 'E74', TRUE),
('Kings Indian, Averbakh, Main Line', 'E75', TRUE),
('Kings Indian, Four Pawns Attack', 'E76', TRUE),
('Kings Indian, Four Pawns Attack, 6.Be2', 'E77', TRUE),
('Kings Indian, Four Pawns Attack, with Be2 & Nf3', 'E78', TRUE),
('Kings Indian, Four Pawns Attack, Main Line', 'E79', TRUE),
('Kings Indian, Sämisch Variation', 'E80', TRUE),
('Kings Indian, Sämisch, 5...O-O', 'E81', TRUE),
('Kings Indian, Sämisch, Double Fianchetto', 'E82', TRUE),
('Kings Indian, Sämisch, 6...Nc6', 'E83', TRUE),
('Kings Indian, Sämisch, Panno Main Line', 'E84', TRUE),
('Kings Indian, Sämisch, Orthodox Variation', 'E85', TRUE),
('Kings Indian, Sämisch, Orthodox, 7.Nge2 c6', 'E86', TRUE),
('Kings Indian, Sämisch, Orthodox, 7.d5', 'E87', TRUE),
('Kings Indian, Sämisch, Orthodox, 7.d5', 'E87', TRUE),
('Kings Indian, Sämisch, Orthodox, Main Line', 'E88', TRUE),
('Kings Indian, Sämisch, Orthodox, 7.d5', 'E89', TRUE),
('Kings Indian, 5.Nf3', 'E90', TRUE),
('Kings Indian, Gligoric-Taimanov System', 'E91', TRUE),
('Kings Indian, Petrosian System', 'E92', TRUE),
('Kings Indian, Petrosian, Main Line', 'E93', TRUE),
('Kings Indian, Petrosian, Stein Defense', 'E94', TRUE),
('Kings Indian, Orthodox, Aronin-Taimanov Variation', 'E95', TRUE),
('Kings Indian, Orthodox, Aronin-Taimanov, Main Line', 'E96', TRUE),
('Kings Indian, Orthodox, Aronin-Taimanov, 9.Ne1', 'E97', TRUE),
('Kings Indian, Orthodox, Aronin-Taimanov, 9.Ne1, Main Line', 'E98', TRUE),
('Kings Indian, Orthodox, Aronin-Taimanov, 9.Ne1, Main Line', 'E99', TRUE);

INSERT INTO Club (Club_Name, Location)
VALUES
-- Europe
('Marshall Chess Club', 'London, England'),
('Royal Chess Club', 'Madrid, Spain'),
('Amsterdam Chess Society', 'Amsterdam, Netherlands'),
('Vienna Chess Circle', 'Vienna, Austria'),
('Stockholm Chess Society', 'Stockholm, Sweden'),
('Polish Chess Academy', 'Warsaw, Poland'),
('Belgrade Chess Club', 'Belgrade, Serbia'),
('Reykjavik Chess Club', 'Reykjavik, Iceland'),
('Prague Chess Masters', 'Prague, Czech Republic'),
('Romanian Chess Federation Club', 'Bucharest, Romania'),
('Helsinki Chess Center', 'Helsinki, Finland'),
('Swiss Chess Academy', 'Zurich, Switzerland'),
('Dublin Chess Union', 'Dublin, Ireland'),
('Copenhagen Chess House', 'Copenhagen, Denmark'),
('Athens Chess Academy', 'Athens, Greece'),

-- Americas
('Manhattan Chess Club', 'New York City, USA'),
('Internet Chess Club', 'Pittsburgh, USA'),
('Chess Club and Scholastic Center', 'Saint Louis, USA'),
('Montreal Chess Club', 'Montreal, Canada'),
('Toronto Chess Federation', 'Toronto, Canada'),
('Vancouver Chess School', 'Vancouver, Canada'),
('Brazilian Chess Club', 'São Paulo, Brazil'),
('Buenos Aires Chess Club', 'Buenos Aires, Argentina'),
('Mexico City Chess Center', 'Mexico City, Mexico'),
('Santiago Chess Federation', 'Santiago, Chile'),

-- Asia
('Moscow Central Chess Club', 'Moscow, Russia'),
('Shanghai Chess Academy', 'Shanghai, China'),
('Beijing Chess Association', 'Beijing, China'),
('Tokyo Chess Club', 'Tokyo, Japan'),
('Seoul Chess Federation', 'Seoul, South Korea'),
('Dubai Chess and Culture Club', 'Dubai, UAE'),
('Tata Steel Chess India', 'Kolkata, India'),
('Mumbai Chess Academy', 'Mumbai, India'),
('Singapore Chess Federation', 'Singapore'),
('Tel Aviv Chess Club', 'Tel Aviv, Israel'),
('Astana Chess Club', 'Astana, Kazakhstan'),
('Ho Chi Minh City Chess Club', 'Ho Chi Minh City, Vietnam'),
('Manila Chess Club', 'Manila, Philippines'),

-- Africa
('Egyptian Chess Federation Club', 'Cairo, Egypt'),
('Johannesburg Chess Center', 'Johannesburg, South Africa'),
('Moroccan Chess Academy', 'Casablanca, Morocco'),
('Kenya Chess Club', 'Nairobi, Kenya'),
('Tunisia Chess Federation', 'Tunis, Tunisia'),

-- Oceania
('Sydney Chess Club', 'Sydney, Australia'),
('Melbourne Chess Club', 'Melbourne, Australia'),
('New Zealand Chess Centre', 'Auckland, New Zealand'),
('Brisbane Chess Club', 'Brisbane, Australia'),

-- Historic/Famous Chess Clubs
('London Chess Club', 'London, England'),
('Café de la Régence', 'Paris, France'),
('Lasker Chess Foundation', 'Berlin, Germany'),
('Botvinnik Chess School', 'Moscow, Russia'),
('Tal Chess Club', 'Riga, Latvia'),
('Fischer Random Chess Club', 'Reykjavik, Iceland'),
('Karpov Chess Academy', 'Moscow, Russia'),
('Kramnik Chess Academy', 'Moscow, Russia'),
('Kasparov Chess Foundation', 'New York City, USA'),
('Anand Chess Academy', 'Chennai, India');

-- Assign random Opening_Id to each Player_Id
INSERT INTO Player_Styles (Player_Id, Opening_Id)
SELECT 
    Player.Player_Id,
    (SELECT Opening.Opening_Id 
     FROM Opening 
     ORDER BY RANDOM() 
     LIMIT 1) AS Random_Opening_Id
FROM 
    Player;


-- Assign random Club_Id to each Player_Id
INSERT INTO Club_Players (Club_Id, Player_Id)
SELECT 
    (SELECT Club.Club_Id 
     FROM Club 
     ORDER BY RANDOM() 
     LIMIT 1) AS Random_Club_Id,
    Player.Player_Id
FROM 
    Player;